### ISSUE TITLE
Xgboost controller is going to CrashLoopBackOff when we create xgboostjobs.xgboostjob.kubeflow.org

### ISSUE THREAD

**Issue by hemantha-kumara** [kubeflow/xgboost-operator#108]
xgboost-operator-deployment is going for CrashLoopBackOff  when the controller is trying to create a pod
here is the log

```
{"level":"info","ts":1612421851.3920496,"logger":"entrypoint","msg":"setting up client for manager"}
{"level":"info","ts":1612421851.392328,"logger":"entrypoint","msg":"setting up manager"}
{"level":"info","ts":1612421853.4459827,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1612421853.446323,"logger":"entrypoint","msg":"Registering Components."}
{"level":"info","ts":1612421853.4463456,"logger":"entrypoint","msg":"setting up scheme"}
{"level":"info","ts":1612421853.446474,"logger":"entrypoint","msg":"Setting up controller"}
{"level":"info","ts":1612421853.4465,"logger":"controller","msg":"Running controller in in-cluster mode"}
there is an error for the input config
{"level":"info","ts":1612421853.4466815,"logger":"controller","msg":"gang scheduling is set: ","gangscheduling":false}
{"level":"info","ts":1612421853.4467366,"logger":"entrypoint","msg":"setting up webhooks"}
{"level":"info","ts":1612421853.4467397,"logger":"entrypoint","msg":"Starting the Cmd."}
{"level":"info","ts":1612421853.4469578,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1612421853.4470663,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"xgboostjob-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1612421853.547405,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"xgboostjob-controller","source":"kind source: /, Kind="}
time="2021-02-04T06:57:33Z" level=info msg="xgboostJob xgboost-dist-iris-test-train-local is created."
{"level":"info","ts":1612421853.6479251,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"xgboostjob-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1612421853.7483046,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"xgboostjob-controller"}
{"level":"info","ts":1612421853.7483666,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"xgboostjob-controller","worker count":1}
time="2021-02-04T06:57:33Z" level=info msg="Reconciling for job xgboost-dist-iris-test-train-local"
time="2021-02-04T06:57:33Z" level=info msg="Need to create new pod: master-0" job=default.xgboost-dist-iris-test-train-local replica-type=master uid=4655e90e-c811-4e63-ad0d-8a45c629253f
E0204 06:57:33.748798       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 348 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14d42c0, 0x23c2fd0)
        /go/pkg/mod/k8s.io/apimachinery@v0.16.10-beta.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.16.10-beta.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14d42c0, 0x23c2fd0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeflow/common/pkg/controller.v1/control.RealPodControl.createPods(0x0, 0x0, 0x18ba160, 0xc000763f00, 0x0, 0x0, 0xc0006f65b9, 0x7, 0xc000984600, 0x188abe0, ...)
        /go/pkg/mod/github.com/kubeflow/common@v0.3.1/pkg/controller.v1/control/pod_control.go:149 +0x175
github.com/kubeflow/common/pkg/controller.v1/control.RealPodControl.CreatePodsWithControllerRef(0x0, 0x0, 0x18ba160, 0xc000763f00, 0xc0006f65b9, 0x7, 0xc000984600, 0x188abe0, 0xc00051e300, 0xc000440780, ...)
        /go/pkg/mod/github.com/kubeflow/common@v0.3.1/pkg/controller.v1/control/pod_control.go:102 +0xe9
github.com/kubeflow/common/pkg/controller.v1/common.(*JobController).createNewPod(0xc000854000, 0x16649c0, 0xc00051e300, 0xc000ab2058, 0x6, 0x16bdee6, 0x1, 0xc000984000, 0x1, 0xc0009b8090, ...)
        /go/pkg/mod/github.com/kubeflow/common@v0.3.1/pkg/controller.v1/common/pod.go:491 +0x7e6
github.com/kubeflow/common/pkg/controller.v1/common.(*JobController).ReconcilePods(0xc000854000, 0x16649c0, 0xc00051e300, 0xc000c74940, 0x0, 0x0, 0x0, 0xc0006f65e4, 0x6, 0xc000984000, ...)
        /go/pkg/mod/github.com/kubeflow/common@v0.3.1/pkg/controller.v1/common/pod.go:367 +0xea4
github.com/kubeflow/common/pkg/controller.v1/common.(*JobController).ReconcileJobs(0xc000854000, 0x16649c0, 0xc00051e300, 0xc0009b8090, 0xc0004f6000, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/kubeflow/common@v0.3.1/pkg/controller.v1/common/job.go:227 +0x1192
github.com/kubeflow/xgboost-operator/pkg/controller/v1/xgboostjob.(*ReconcileXGBoostJob).Reconcile(0xc000854000, 0xc0006f65b9, 0x7, 0xc0000caab0, 0x22, 0xc000737cd8, 0xc00021a630, 0xc0001103f8, 0x1891900)
        /go/src/github.com/kubeflow/xgboost-operator/pkg/controller/v1/xgboostjob/xgboostjob_controller.go:228 +0x3f1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001ff380, 0x152b240, 0xc00036c100, 0x23e3f00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001ff380, 0xc0000ab100)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001ff380)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00007f360)
        /go/pkg/mod/k8s.io/apimachinery@v0.16.10-beta.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00007f360, 0x3b9aca00, 0x0, 0x1, 0xc0000aad80)
        /go/pkg/mod/k8s.io/apimachinery@v0.16.10-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00007f360, 0x3b9aca00, 0xc0000aad80)
        /go/pkg/mod/k8s.io/apimachinery@v0.16.10-beta.0/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:193 +0x328
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x1223fd5]

goroutine 348 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.16.10-beta.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x14d42c0, 0x23c2fd0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeflow/common/pkg/controller.v1/control.RealPodControl.createPods(0x0, 0x0, 0x18ba160, 0xc000763f00, 0x0, 0x0, 0xc0006f65b9, 0x7, 0xc000984600, 0x188abe0, ...)
        /go/pkg/mod/github.com/kubeflow/common@v0.3.1/pkg/controller.v1/control/pod_control.go:149 +0x175
github.com/kubeflow/common/pkg/controller.v1/control.RealPodControl.CreatePodsWithControllerRef(0x0, 0x0, 0x18ba160, 0xc000763f00, 0xc0006f65b9, 0x7, 0xc000984600, 0x188abe0, 0xc00051e300, 0xc000440780, ...)
        /go/pkg/mod/github.com/kubeflow/common@v0.3.1/pkg/controller.v1/control/pod_control.go:102 +0xe9
github.com/kubeflow/common/pkg/controller.v1/common.(*JobController).createNewPod(0xc000854000, 0x16649c0, 0xc00051e300, 0xc000ab2058, 0x6, 0x16bdee6, 0x1, 0xc000984000, 0x1, 0xc0009b8090, ...)
        /go/pkg/mod/github.com/kubeflow/common@v0.3.1/pkg/controller.v1/common/pod.go:491 +0x7e6
github.com/kubeflow/common/pkg/controller.v1/common.(*JobController).ReconcilePods(0xc000854000, 0x16649c0, 0xc00051e300, 0xc000c74940, 0x0, 0x0, 0x0, 0xc0006f65e4, 0x6, 0xc000984000, ...)
        /go/pkg/mod/github.com/kubeflow/common@v0.3.1/pkg/controller.v1/common/pod.go:367 +0xea4
github.com/kubeflow/common/pkg/controller.v1/common.(*JobController).ReconcileJobs(0xc000854000, 0x16649c0, 0xc00051e300, 0xc0009b8090, 0xc0004f6000, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/kubeflow/common@v0.3.1/pkg/controller.v1/common/job.go:227 +0x1192
github.com/kubeflow/xgboost-operator/pkg/controller/v1/xgboostjob.(*ReconcileXGBoostJob).Reconcile(0xc000854000, 0xc0006f65b9, 0x7, 0xc0000caab0, 0x22, 0xc000737cd8, 0xc00021a630, 0xc0001103f8, 0x1891900)
        /go/src/github.com/kubeflow/xgboost-operator/pkg/controller/v1/xgboostjob/xgboostjob_controller.go:228 +0x3f1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001ff380, 0x152b240, 0xc00036c100, 0x23e3f00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001ff380, 0xc0000ab100)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001ff380)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00007f360)
        /go/pkg/mod/k8s.io/apimachinery@v0.16.10-beta.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00007f360, 0x3b9aca00, 0x0, 0x1, 0xc0000aad80)
        /go/pkg/mod/k8s.io/apimachinery@v0.16.10-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00007f360, 0x3b9aca00, 0xc0000aad80)
        /go/pkg/mod/k8s.io/apimachinery@v0.16.10-beta.0/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:193 +0x328
```

**Comment by Focke-Wulf** [comment]
I also have this problem

**Comment by OyutianO** [comment]
me too

**Comment by asahalyft** [comment]
I have build a docker image based on the latest patch - you are welcome to try it if that helps you to test docker.io/anindyas/xgboost-operator:vmaster-edccbfefc

**Comment by Jeffwan** [comment]
sorry for late response. #116 resolves this issue

**Comment by Jeffwan** [comment]
Please check latest crds and controllers
