### ISSUE TITLE
XGBoost example(xgboost-dist) not working

### ISSUE THREAD

**Issue by RudraprakashR** [kubeflow/xgboost-operator#32]
Hi,
When I try to execute the xgboost-dist example on kubernetes, it give me the following error:
https://github.com/kubeflow/xgboost-operator/tree/master/config/samples/xgboost-dist

When train job is run :
```
[root@cluster01-control-host01 xgboost-dist]# kubectl logs xgboost-train-worker-1
starting the train job
starting to extract system env
extract the Rabit env from cluster : xgboost-train-master-0, port: 9991, rank: 1, word_size: 3
##### Rabit rank setup with below envs #####
DMLC_NUM_WORKER=3
DMLC_TRACKER_URI=xgboost-train-master-0
DMLC_TRACKER_PORT=9991
DMLC_TASK_ID=1
retry connect to ip(retry time 1): [xgboost-train-master-0]
##### Rabit rank = 0
Read data from IRIS data source with range from 0 to 50
starting to train xgboost at node with rank 0
[0] save global checkpoint #1
[0] save global checkpoint #2
[0] save global checkpoint #3
[0] save global checkpoint #4
[0] save global checkpoint #5
[0] save global checkpoint #6
[0] save global checkpoint #7
[0] save global checkpoint #8
[0] save global checkpoint #9
[0] save global checkpoint #10
[0] save global checkpoint #11
[0] save global checkpoint #12
[0] save global checkpoint #13
[0] save global checkpoint #14
[0] save global checkpoint #15
[0] save global checkpoint #16
[0] save global checkpoint #17
[0] save global checkpoint #18
[0] save global checkpoint #19
[0] save global checkpoint #20
finish xgboost training at node with rank 0
xgboost training job finished!
finish the model training, and start to dump model
Traceback (most recent call last):
  File "/opt/mlkube/main.py", line 89, in <module>
    main(main_args)
  File "/opt/mlkube/main.py", line 35, in main
    dump_model(model, model_storage_type, model_path, args)
  File "/opt/mlkube/utils.py", line 140, in dump_model
    oss_param = parse_parameters(args.oss_param, ",", ":")
  File "/opt/mlkube/utils.py", line 285, in parse_parameters
    ky_paris = input.split(splitter_between)
AttributeError: 'NoneType' object has no attribute 'split'
```

also sometimes it gives the following error:

```
[root@cluster01-control-host01 xgboost-dist]# kubectl logs xgboost-dist-iris-test-train-worker-0
starting the train job
starting to extract system env
extract the Rabit env from cluster : xgboost-dist-iris-test-train-master-0, port: 9991, rank: 0, word_size: 3
start the master node
start listen on 0.0.0.0:9991
###### RabitTracker Setup Finished ######
##### Rabit rank setup with below envs #####
DMLC_NUM_WORKER=3
DMLC_TRACKER_URI=xgboost-dist-iris-test-train-master-0
DMLC_TRACKER_PORT=9991
DMLC_TASK_ID=0
cannot obtain address of xgboost-dist-iris-test-train-master-0
```

However this is very sporadic this job goes to completion state but sometime it throws the above said error.

When predict job is run :
Worker-1 log:
```
starting the predict job
starting to extract system env
extract the Rabit env from cluster : xgboost-master-0, port: 9991, rank: 1, word_size: 3
Read data from IRIS datasource with range from 50 to 100
Traceback (most recent call last):
  File "/opt/mlkube/main.py", line 89, in <module>
    main(main_args)
  File "/opt/mlkube/main.py", line 25, in main
    predict(args)
  File "/opt/mlkube/predict.py", line 32, in predict
    booster = read_model("oss", model_path, args)
  File "/opt/mlkube/utils.py", line 169, in read_model
    oss_param = parse_parameters(args.oss_param, ",", ":")
  File "/opt/mlkube/utils.py", line 295, in parse_parameters
    value = conf[1]
IndexError: list index out of range
```

The same log is observed in both the workers of predict.

**Comment by merlintang** [comment]
@RudraprakashR thanks for your testing on the xgboost operator. as we found from this log, the training is finished. the current issue is that the way to store the trained model. currently, we only support the train model to be stored at [OSS[(https://www.alibabacloud.com/product/oss). thus, you need to specific the oss storage parameter in the https://github.com/kubeflow/xgboost-operator/blob/master/config/samples/xgboost-dist/xgboostjob_v1alpha1_iris_train.yaml#L28.

**Comment by hemantha-kumara** [comment]
@merlintang  is there any way we can configure other storage?

**Comment by merlintang** [comment]
yes, we can set up the s3 as the storage via the s3 bucket. you can add the
s3 storage config at here:
https://github.com/kubeflow/xgboost-operator/blob/master/config/samples/xgboost-dist/utils.py#L139
if
you can provide the s3 bucket related information, then the model could be
stored.

**Comment by terrytangyuan** [comment]
@merlintang I think we can dump model to a local path where that path is mounted from a shared storage.

**Comment by merlintang** [comment]
yes, it is good point.

**Comment by RudraprakashR** [comment]
The example works fine now. 
I have updated the parameter list by
 --oss_param=endpoint:http://oss-ap-south-1.aliyuncs.com,access_id:XXXXXXXXXXX,access_key:XXXXXXXXXXX,access_bucket:XXXXXXXXXXX

where XXXXXXXXXXX can be replaced with actual information

Also mentioned the same in README.md.

Thank you for the support @merlintang @terrytangyuan
