### ISSUE TITLE
xgboostjob_v1alpha1_iris_train example doesn't work on master

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/xgboost-operator#76]
I tested against changes on master and example doesn't work. I even tried version on `Commits on Oct 9, 2019`. It doesn't work for me. Can someone help verify? 

Apply examples. 
```
kubectl create -f config/samples/xgboost-dist/xgboostjob_v1alpha1_iris_train.yaml
```

```
xgboost-dist-iris-test-train-master-0   0/1     Error       0          35s
xgboost-dist-iris-test-train-worker-0   0/1     Completed   0          35s
xgboost-dist-iris-test-train-worker-1   0/1     Completed   0          35s
```

Logs:
```
[0] save global checkpoint #20
finish xgboost training at node with rank 0
xgboost training job finished!
@tracker All nodes finishes job
@tracker 15.337999820709229 secs between node start and job finish
finish the model training, and start to dump model
Traceback (most recent call last):
  File "/opt/mlkube/main.py", line 89, in <module>
    main(main_args)
  File "/opt/mlkube/main.py", line 35, in main
    dump_model(model, model_storage_type, model_path, args)
  File "/opt/mlkube/utils.py", line 140, in dump_model
    oss_param = parse_parameters(args.oss_param, ",", ":")
  File "/opt/mlkube/utils.py", line 295, in parse_parameters
    value = conf[1]
IndexError: list index out of range
```

**Comment by merlintang** [comment]
maybe you need to use the local model

**Comment by terrytangyuan** [comment]
Looks like it fails to parse OSS config params and you don't have OSS configured properly. Perhaps you want to use https://github.com/kubeflow/xgboost-operator/blob/master/config/samples/xgboost-dist/xgboostjob_v1alpha1_iris_train_local.yaml instead which trains the model locally.

**Comment by Jeffwan** [comment]
I change the model path to /tmp and it works. Close this issue
